### PR TITLE
implements a 'showCreateDate' configuration option

### PR DESCRIPTION
**Pull request by koenig**
I needed a appCache manifest without the creation date, so I implemented a configuration option, to be able to hide the date.

### CODE REVIEW

**Comment by ssured** [comment]
The create date has an extra function; it acts as a unique identifier so no two manifest files are the same. Updating the app will then always result in a cache update on the client. I'll update the PR with a random string instead of a date and then merge

**Comment by koenig** [comment]
I solved the cache update issue in one project by fingerprinting files. So I wanted to be able to remove the create date to avoid reload of cache on every manifest creation.

**Comment by ssured** [comment]
By fingerprinting files, the cache manifest will change and thus trigger a reload, right? Or am I missing something?

**Comment by koenig** [comment]
correctly

**Comment by koenig** [comment]
the browser just checks if the manifest file changed (in any way) and if so refreshes the cache.

**Pull request merged**
